name: Remote Dispatch Action Initiator

on:
  push:
  repository_dispatch:
  workflow_dispatch: # Permite ejecutar manualmente

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Event
        run: |
         curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"update-pdf\", \"client_payload\": {\"run\": \"true\"}}"
